version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
    - 3.6.0
  - dependency-name: timex
    versions:
    - 3.6.3
    - 3.6.4
    - 3.7.1
    - 3.7.3
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: sobelow
    versions:
    - 0.11.0
  - dependency-name: tesla
    versions:
    - 1.4.0
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
  - dependency-name: exop
    versions:
    - 1.4.2
